model_params:
  name: 'CTMCQVAE'
  in_channels: 3
  embedding_dim: 64
  action_dim: 6
  hidden_dims: [64, 128, 256]
  causal_hidden_dim: 800
  num_embeddings: 16
  img_size: 64
  codebooks: 1
  beta: 0.25
  c_alpha: 0.5
  c_beta: 0.1
  c_gamma: 0.4
  c_epsilon: 0.2
  noise: "endo"

data_params:
  data_path: "Data/"
  dataset_name: "TCars3D"
  train_batch_size: 16
  val_batch_size:  16
  patch_size: 64
  num_workers: 4
  mode: ["base","base","action","causal"]
  limit: 10000


exp_params:
  # metrics: ["DCI", "MIG", "SAP", "FactorVaeScore"]
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.98
  kld_weight: 0.00025
  manual_seed: 1250
  find_unused_parameters: False

trainer_params:
  gpus: [0]
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: 'CTMCQVAE'
