model_params:
  name: 'CTMCQVAE'
  in_channels: 3
  embedding_dim: 64
  action_dim: 20
  hidden_dims: [128, 256]
  causal_hidden_dim: 800
  num_embeddings: 16
  img_size: 64
  codebooks: 1
  beta: 0.25
  causal_alpha: 0.7
  causal_beta: 0.4
  causal_gamma: 0.9

data_params:
  data_path: "Data/"
  train_batch_size: 16
  val_batch_size:  16
  patch_size: 64
  num_workers: 4
  mode: "base"
  noise: "off"


exp_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.98
  kld_weight: 0.00025
  manual_seed: 1250
  find_unused_parameters: False

trainer_params:
  gpus: [0]
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: 'CTMCQVAE'
