model_params:
  name: 'CTMCQVAE'
  in_channels: 3
  embedding_dim: 128
  action_dim: 12
  hidden_dims: [64, 128, 256]
  causal_hidden_dim: 800
  causal_nb_heads: 4
  num_embeddings: 32
  img_size: 64
  codebooks: 2
  beta: 0.25
  gamma: 0.05
  c_alpha: 1.0
  c_beta: 0.1
  c_delta: 0.001
  c_epsilon: 0.1
  noise: "endo"

data_params:
  data_path: "Data/"
  dataset_name: "TShapes3D"
  train_batch_size: 8
  val_batch_size: 8
  patch_size: 64
  num_workers: 4
  limit: 16000
  # distributed: False

exp_params:
  # metrics: ["DCI", "MIG", "SAP", "FactorVaeScore"]
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.98
  kld_weight: 0.00025
  manual_seed: 1250
  find_unused_parameters: True

trainer_params:
  gpus: [0]
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: 'CTMCQVAE'
